import os
import pandas as pd
import numpy as np

from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QPushButton, 
                               QLabel, QFileDialog, QGroupBox, QMessageBox, QComboBox, QFormLayout)
from PySide6.QtCore import Qt

import matplotlib
matplotlib.use('QtAgg')
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

def compute_velocity(accel, time):
    """
    Oblicza prędkość przez całkowanie przyspieszenia (reguła trapezowa)
    Zwraca tablicę tej samej długości co accel
    """
    dt = np.diff(time)
    vel = np.zeros(len(accel))
    vel[1:] = np.cumsum( (accel[:-1] + accel[1:]) / 2 * dt )
    return vel

class ModuleTarget(QWidget):
    def __init__(self):
        super().__init__()
        self.data = None
        self.init_ui()
        
    def init_ui(self):
        main_layout = QHBoxLayout(self)
        
        # Left Panel - Controls
        control_panel = QWidget()
        control_panel.setFixedWidth(350)
        control_layout = QVBoxLayout(control_panel)
        
        # 1. Load File
        group_load = QGroupBox("1. Wczytaj wycięty Event")
        load_layout = QVBoxLayout()
        self.btn_load = QPushButton("Load Event (.xlsx, .csv)")
        self.btn_load.clicked.connect(self.load_file)
        self.lbl_file = QLabel("Brak pliku")
        self.lbl_file.setWordWrap(True)
        load_layout.addWidget(self.btn_load)
        load_layout.addWidget(self.lbl_file)
        group_load.setLayout(load_layout)
        control_layout.addWidget(group_load)
        
        # 2. Map Columns (in case it wasn't pre-mapped by module 1)
        group_map = QGroupBox("2. Mapowanie Kolumn (jeśli puste)")
        map_layout = QFormLayout()
        
        self.combo_time = QComboBox()
        self.combo_ax = QComboBox()
        self.combo_ay = QComboBox()
        self.combo_az = QComboBox()
        
        map_layout.addRow("Time:", self.combo_time)
        map_layout.addRow("Accel X (m/s²):", self.combo_ax)
        map_layout.addRow("Accel Y (m/s²):", self.combo_ay)
        map_layout.addRow("Accel Z (m/s²):", self.combo_az)
        group_map.setLayout(map_layout)
        control_layout.addWidget(group_map)
        
        # 3. Analyze
        group_actions = QGroupBox("3. Obliczenia Prędkości")
        actions_layout = QVBoxLayout()
        self.btn_analyze = QPushButton("Analizuj Prędkość i Generuj Raport")
        self.btn_analyze.clicked.connect(self.analyze_event)
        self.btn_analyze.setEnabled(False)
        self.btn_analyze.setStyleSheet("background-color: #3498DB; color: white; font-weight: bold;")
        actions_layout.addWidget(self.btn_analyze)
        group_actions.setLayout(actions_layout)
        control_layout.addWidget(group_actions)
        
        # 4. Summary Text
        group_summary = QGroupBox("Raport Zdarzenia")
        summary_layout = QVBoxLayout()
        self.lbl_summary = QLabel("Wczytaj plik i kliknij Analizuj.")
        self.lbl_summary.setTextInteractionFlags(Qt.TextSelectableByMouse)
        summary_layout.addWidget(self.lbl_summary)
        group_summary.setLayout(summary_layout)
        control_layout.addWidget(group_summary)
        
        control_layout.addStretch()
        
        # Right Panel - Plots
        plot_panel = QWidget()
        plot_layout = QVBoxLayout(plot_panel)
        
        self.figure = Figure(figsize=(8, 8))
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, self)
        
        plot_layout.addWidget(self.toolbar)
        plot_layout.addWidget(self.canvas)
        
        main_layout.addWidget(control_panel)
        main_layout.addWidget(plot_panel, stretch=1)

    def load_file(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Wybierz plik z eventem", "", "Excel Files (*.xlsx);;CSV Files (*.csv);;All Files (*)")
        if not file_path:
            return
            
        self.lbl_file.setText(os.path.basename(file_path))
        
        try:
            if file_path.endswith('.csv'):
                self.data = pd.read_csv(file_path)
            else:
                self.data = pd.read_excel(file_path)
        except Exception as e:
            QMessageBox.critical(self, "Błąd", f"Nie udało się wczytać pliku: {str(e)}")
            return
            
        # Update combo boxes
        columns = list(self.data.columns)
        combos = [self.combo_time, self.combo_ax, self.combo_ay, self.combo_az]
                  
        for combo in combos:
            combo.clear()
            combo.addItems(["--- Brak ---"] + columns)
            
        # Auto-guess columns based on common names or the ones generated by Module 1/Notebook
        for i, col in enumerate(columns):
            col_lower = col.lower()
            if col == 'Time' or 'time' in col_lower:
                self.combo_time.setCurrentIndex(i + 1)
            elif 'accel' in col_lower and 'x' in col_lower:
                self.combo_ax.setCurrentIndex(i + 1)
            elif 'accel' in col_lower and 'y' in col_lower:
                self.combo_ay.setCurrentIndex(i + 1)
            elif 'accel' in col_lower and 'z' in col_lower:
                self.combo_az.setCurrentIndex(i + 1)
                
        # Overwrite with exact matches if they exist (highest priority)
        for i, col in enumerate(columns):
            if col in ['ax', '2x']:
                self.combo_ax.setCurrentIndex(i + 1)
            elif col in ['ay', '2y']:
                self.combo_ay.setCurrentIndex(i + 1)
            elif col in ['az', '2z']:
                self.combo_az.setCurrentIndex(i + 1)
                
        self.btn_analyze.setEnabled(True)
        self.lbl_summary.setText("Dane wczytane. Gotowy do analizy.")

    def analyze_event(self):
        if self.data is None:
            return
            
        time_col = self.combo_time.currentText()
        ax_col = self.combo_ax.currentText()
        ay_col = self.combo_ay.currentText()
        az_col = self.combo_az.currentText()
        
        if time_col == "--- Brak ---" or ax_col == "--- Brak ---" or ay_col == "--- Brak ---" or az_col == "--- Brak ---":
            QMessageBox.warning(self, "Uwaga", "Musisz wybrać kolumnę czasu oraz kolumny przyspieszenia X, Y, Z.")
            return
            
        try:
            df = self.data.copy()
            
            # Extract data
            time_vals = df[time_col].values
            ax_vals = df[ax_col].values
            ay_vals = df[ay_col].values
            az_vals = df[az_col].values
            
            # Compute velocities
            df['vel_x'] = compute_velocity(ax_vals, time_vals)
            df['vel_y'] = compute_velocity(ay_vals, time_vals)
            df['vel_z'] = compute_velocity(az_vals, time_vals)
            
            # Resultant Velocity
            df['vel_resultant'] = np.sqrt(df['vel_x']**2 + df['vel_y']**2 + df['vel_z']**2)
            
            # Summary report
            max_vx = df['vel_x'].max()
            max_vy = df['vel_y'].max()
            max_vz = df['vel_z'].max()
            max_res = df['vel_resultant'].max()
            
            summary_text = (
                f"=== MAX PRĘDKOŚCI ===\n"
                f"Max vel_x: {max_vx:.2f} m/s\n"
                f"Max vel_y: {max_vy:.2f} m/s\n"
                f"Max vel_z: {max_vz:.2f} m/s\n"
                f"MAX Wypadkowa: {max_res:.2f} m/s\n\n"
            )
            
            # Wyszukanie momentu maksymalnej siły
            if 'resultant_force' in df.columns:
                max_force_idx = df['resultant_force'].idxmax()
                peak_time = df[time_col].loc[max_force_idx]
                peak_force = df['resultant_force'].loc[max_force_idx]
                
                # Przyspieszenie i prędkość w momencie uderzenia
                if 'resultant_acceleration' in df.columns:
                    peak_accel = df['resultant_acceleration'].loc[max_force_idx]
                else:
                    peak_accel = 0
                peak_vel = df['vel_resultant'].loc[max_force_idx]
                
                peak_ax = df[ax_col].loc[max_force_idx]
                peak_ay = df[ay_col].loc[max_force_idx]
                peak_az = df[az_col].loc[max_force_idx]
                peak_vx = df['vel_x'].loc[max_force_idx]
                peak_vy = df['vel_y'].loc[max_force_idx]
                peak_vz = df['vel_z'].loc[max_force_idx]
                
                summary_text += (
                    f"=== W MOMENCIE MAX FORCE ===\n"
                    f"Czas uderzenia: {peak_time:.3f} s\n"
                    f"Max Siła (Resultant): {peak_force:.0f} N\n\n"
                    f"Przyspieszenie X: {peak_ax:.1f} m/s²\n"
                    f"Przyspieszenie Y: {peak_ay:.1f} m/s²\n"
                    f"Przyspieszenie Z: {peak_az:.1f} m/s²\n"
                    f"Przyspieszenie Wypadkowe: {peak_accel:.1f} m/s²\n\n"
                    f"Prędkość X: {peak_vx:.2f} m/s\n"
                    f"Prędkość Y: {peak_vy:.2f} m/s\n"
                    f"Prędkość Z: {peak_vz:.2f} m/s\n"
                    f"Prędkość Wypadkowa: {peak_vel:.2f} m/s\n"
                )
                
                has_force = True
            else:
                has_force = False

            self.lbl_summary.setText(summary_text)

            # Plot
            self.figure.clear()
            axes = self.figure.subplots(3, 1, sharex=True)
            
            # 1. Force
            if has_force:
                axes[0].plot(df[time_col], df['resultant_force'], color='#E74C3C', linewidth=1.5)
                axes[0].set_ylabel('Force (N)')
                axes[0].axvline(peak_time, color='gray', linestyle='--', alpha=0.7)
                axes[0].plot(peak_time, peak_force, marker='o', markersize=10, markerfacecolor='gold', markeredgecolor='black')
                axes[0].text(peak_time + 0.01, peak_force, f'Max Force\n{peak_force:.0f} N', color='#E74C3C', fontweight='bold', va='top')
            else:
                axes[0].text(0.5, 0.5, 'Brak kolumny resultant_force', transform=axes[0].transAxes, ha='center')
            axes[0].grid(True, alpha=0.3)
            axes[0].set_title('Event - Resultant Force, Acceleration & Velocity', fontweight='bold')
            
            # 2. Acceleration
            if 'resultant_acceleration' in df.columns:
                axes[1].plot(df[time_col], df['resultant_acceleration'], color='#3498DB', linewidth=1.5)
                if has_force:
                    axes[1].axvline(peak_time, color='gray', linestyle='--', alpha=0.7)
                    axes[1].plot(peak_time, peak_accel, marker='o', markersize=10, markerfacecolor='gold', markeredgecolor='black')
                    axes[1].text(peak_time + 0.01, peak_accel, f'{peak_accel:.1f} m/s²', color='#3498DB', fontweight='bold', va='center')
            axes[1].set_ylabel('Acceleration (m/s²)')
            axes[1].grid(True, alpha=0.3)
            
            # 3. Velocity
            axes[2].plot(df[time_col], df['vel_resultant'], color='#2ECC71', linewidth=1.6)
            axes[2].fill_between(df[time_col], df['vel_resultant'], alpha=0.15, color='#2ECC71')
            if has_force:
                axes[2].axvline(peak_time, color='gray', linestyle='--', alpha=0.7)
                axes[2].plot(peak_time, peak_vel, marker='o', markersize=10, markerfacecolor='gold', markeredgecolor='black')
                axes[2].text(peak_time + 0.01, peak_vel, f'{peak_vel:.2f} m/s', color='#2ECC71', fontweight='bold', va='top')
            axes[2].set_ylabel('Velocity (m/s)')
            axes[2].set_xlabel('Time (s)')
            axes[2].grid(True, alpha=0.3)
            
            self.figure.tight_layout()
            self.canvas.draw()
            
        except Exception as e:
            QMessageBox.critical(self, "Błąd", f"Wystąpił błąd podczas analizy:\n{str(e)}")
